///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NodeJSSmoke
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NodeJSSmokeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0f1c0457-6f56-4ea7-88c1-02a0bd8bfb2e")]
    public partial class NodeJSSmokeRepository : RepoGenBaseFolder
    {
        static NodeJSSmokeRepository instance = new NodeJSSmokeRepository();
        NodeJSSmokeRepositoryFolders.HomeTheExampleAppAppFolder _hometheexampleapp;

        /// <summary>
        /// Gets the singleton class instance representing the NodeJSSmokeRepository element repository.
        /// </summary>
        [RepositoryFolder("0f1c0457-6f56-4ea7-88c1-02a0bd8bfb2e")]
        public static NodeJSSmokeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NodeJSSmokeRepository() 
            : base("NodeJSSmokeRepository", "/", null, 0, false, "0f1c0457-6f56-4ea7-88c1-02a0bd8bfb2e", ".\\RepositoryImages\\NodeJSSmokeRepository0f1c0457.rximgres")
        {
            _hometheexampleapp = new NodeJSSmokeRepositoryFolders.HomeTheExampleAppAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0f1c0457-6f56-4ea7-88c1-02a0bd8bfb2e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HomeTheExampleApp folder.
        /// </summary>
        [RepositoryFolder("03e225d9-e624-40de-8dd4-f6d4d76f85c7")]
        public virtual NodeJSSmokeRepositoryFolders.HomeTheExampleAppAppFolder HomeTheExampleApp
        {
            get { return _hometheexampleapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class NodeJSSmokeRepositoryFolders
    {
        /// <summary>
        /// The HomeTheExampleAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("03e225d9-e624-40de-8dd4-f6d4d76f85c7")]
        public partial class HomeTheExampleAppAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _homeInfo;
            RepoItemInfo _viewcourseInfo;
            RepoItemInfo _learnhowtobuildyourownapplicationsInfo;

            /// <summary>
            /// Creates a new HomeTheExampleApp  folder.
            /// </summary>
            public HomeTheExampleAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HomeTheExampleApp", "/dom[@domain='localhost:3000']", parentFolder, 30000, null, false, "03e225d9-e624-40de-8dd4-f6d4d76f85c7", "")
            {
                _homeInfo = new RepoItemInfo(this, "Home", "?/?/main/div[1]//nav/ul/?/?/a[@innertext='Home']", 30000, null, "284873df-22f3-4138-bd99-7709dc1c859b");
                _viewcourseInfo = new RepoItemInfo(this, "ViewCourse", "body/main/div[2]/div[2]/div/div/div[2]/div[3]/a[@innertext='view course']", 30000, null, "f2aaeb35-30df-4706-830a-986652c8c70e");
                _learnhowtobuildyourownapplicationsInfo = new RepoItemInfo(this, "LearnHowToBuildYourOwnApplications", "body/main/div[2]/div[2]/div/div/div[2]/div[2]/p[@innertext>'Learn how to build your own']", 30000, null, "74ec0a0b-cfa9-48fa-ac64-b96973d8ce9b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("03e225d9-e624-40de-8dd4-f6d4d76f85c7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("03e225d9-e624-40de-8dd4-f6d4d76f85c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("284873df-22f3-4138-bd99-7709dc1c859b")]
            public virtual Ranorex.ATag Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("284873df-22f3-4138-bd99-7709dc1c859b")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The ViewCourse item.
            /// </summary>
            [RepositoryItem("f2aaeb35-30df-4706-830a-986652c8c70e")]
            public virtual Ranorex.ATag ViewCourse
            {
                get
                {
                    return _viewcourseInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ViewCourse item info.
            /// </summary>
            [RepositoryItemInfo("f2aaeb35-30df-4706-830a-986652c8c70e")]
            public virtual RepoItemInfo ViewCourseInfo
            {
                get
                {
                    return _viewcourseInfo;
                }
            }

            /// <summary>
            /// The LearnHowToBuildYourOwnApplications item.
            /// </summary>
            [RepositoryItem("74ec0a0b-cfa9-48fa-ac64-b96973d8ce9b")]
            public virtual Ranorex.PTag LearnHowToBuildYourOwnApplications
            {
                get
                {
                    return _learnhowtobuildyourownapplicationsInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The LearnHowToBuildYourOwnApplications item info.
            /// </summary>
            [RepositoryItemInfo("74ec0a0b-cfa9-48fa-ac64-b96973d8ce9b")]
            public virtual RepoItemInfo LearnHowToBuildYourOwnApplicationsInfo
            {
                get
                {
                    return _learnhowtobuildyourownapplicationsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
