///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.Diagnostics;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NodeJSSmoke
{
    public partial class OpenBrowser
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void HosttheBuild()
        {
        		 string path = Directory.GetParent(Ranorex.Core.Testing.TestSuite.WorkingDirectory).ToString();
				 path= Path.GetFullPath(path + "../../../../../");
             	 Process process = new Process();
			     ProcessStartInfo start = new ProcessStartInfo("cmd", "/c npm run start:dev");
			     start.WorkingDirectory= path;
			     process.StartInfo = start;		    
			     process.Start();
			     Thread.Sleep(5000);
				
			    
        }

    }
}
