///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NodeJSSmoke
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestBrowser recording.
    /// </summary>
    [TestModule("9ce0ac3c-9e38-4c7f-8117-1cc3ee0bf058", ModuleType.Recording, 1)]
    public partial class TestBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NodeJSSmokeRepository repository.
        /// </summary>
        public static NodeJSSmokeRepository repo = NodeJSSmokeRepository.Instance;

        static TestBrowser instance = new TestBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeTheExampleApp.Home' at 31;18.", repo.HomeTheExampleApp.HomeInfo, new RecordItemIndex(0));
            repo.HomeTheExampleApp.Home.Click("31;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HomeTheExampleApp.ViewCourse'.", repo.HomeTheExampleApp.ViewCourseInfo, new RecordItemIndex(1));
            Validate.Exists(repo.HomeTheExampleApp.ViewCourseInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeTheExampleApp.LearnHowToBuildYourOwnApplications' at 155;14.", repo.HomeTheExampleApp.LearnHowToBuildYourOwnApplicationsInfo, new RecordItemIndex(2));
            repo.HomeTheExampleApp.LearnHowToBuildYourOwnApplications.Click("155;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HomeTheExampleApp.LearnHowToBuildYourOwnApplications' at 152;13.", repo.HomeTheExampleApp.LearnHowToBuildYourOwnApplicationsInfo, new RecordItemIndex(3));
            repo.HomeTheExampleApp.LearnHowToBuildYourOwnApplications.Click("152;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
